wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.1
    framework: huggingface
    huggingface_version: 4.10.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683924464.08427
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.8.5
      5: 0.15.1
      6: 4.10.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
